/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.sql.Date;

import jakarta.persistence.*;
import lombok.*;

/**
 * JPA entity class for "Bookingdetails"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="bookingdetails" )
@Getter
@Setter
public class Bookingdetails {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id ;

    private Date playdate;

    private Double price ;

    @ManyToOne
    private Field field ;

    @ManyToOne
    private Bookings bookings ;

    @ManyToOne
    private Shifts shifts ;

}
