/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.sql.Date;
import java.util.List;

import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonIgnore;


import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import lombok.*;

@AllArgsConstructor
@NoArgsConstructor
@Entity
@Getter
@Setter
@Table(name="bookings" )
public class Bookings {

    @Id
    @GeneratedValue(strategy=GenerationType.IDENTITY)
    private Integer id;

    private Date bookingDate;

    private Double bookingPrice;

    private String phone;

    private String note;

    private String fullName;

    private String bookingStatus;

    @ManyToOne
    private User user;

    @OneToMany(mappedBy = "bookings", cascade = CascadeType.REMOVE)
    private List<Bookingdetails> bookingdetails;

}
