/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;
import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name="categories" )
@Getter
@Setter
public class Categories {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Long id ;

    private String categoryName ;

}
