/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.sql.Date;

import jakarta.persistence.*;
import jakarta.validation.constraints.Size;
import lombok.*;

@Entity
@Table(name="eventweb")
@Setter
@Getter
public class Eventweb {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    private String nameEvent;

    private Date dateStart;

    private Date dateEnd;

    private String image;

    @Column(columnDefinition = "LONGTEXT")
    private String descriptions;
    
    private String eventType;

}
