/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.util.List;


import com.fasterxml.jackson.annotation.JsonIgnore;


import jakarta.persistence.*;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.Size;
import lombok.*;

/**
 * JPA entity class for "Field"
 *
 * @author Telosys
 *
 */
@Entity
@Table(name="field" )
@Getter
@Setter
public class Field {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    private String nameField;

    @Column(columnDefinition = "LONGTEXT")
    private String descriptionField;

    private Double price;

    private String image;

    private String address;

    private Boolean status;

    @ManyToOne
    private Sporttype sporttype;

    @OneToMany(mappedBy="field")
    private List<Bookingdetails> listOfBookingdetails ; 

}
