/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;


import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import jakarta.persistence.*;
import lombok.*;

@Entity
@Table(name = "orders")
@Getter
@Setter
public class Orders {

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    private Date createDate;

    private String address;

    private String note;

    private String orderStatus;

    private Boolean paymentStatus;

    private Double totalPrice;

    private String fullName;

    private String phone;

    @ManyToOne
    private User user;

    @OneToMany(mappedBy="orders")
    private List<Orderdetails> orderDetails ; 

}
