/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;


@Entity
@Table(name = "orderdetails")
@Getter
@Setter
public class Orderdetails{

	@Id
	@GeneratedValue(strategy= GenerationType.IDENTITY)
	private Integer id;

	Double price;

	Integer quantity;

	@ManyToOne
	private Products products;

	@ManyToOne
	private Orders orders;

}
