/*
 * Created on 2023-06-14 ( 09:06:03 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.web.entity;

import java.io.Serializable;
import java.time.LocalDate;
import java.util.Date;
import java.util.List;


import com.fasterxml.jackson.annotation.JsonIgnore;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Table(name="teams")
@Getter
@Setter
public class Teams{

    @Id
    @GeneratedValue(strategy= GenerationType.IDENTITY)
    private Integer id;

    private String nameTeam;

    private Integer quantity;

    private String avatar;

    private String contact;

    private String descriptions;

    private String username;

    private LocalDate createDate;

    @ManyToOne
    private Sporttype sportType;

    @ManyToOne
    private User user;

    @OneToMany(mappedBy = "teams", cascade = CascadeType.REMOVE)
    private List<Teamdetails> teamdetails;

    @Transient
    private Boolean daThamGia;

    @Transient
    private Integer activeMember;

    public Integer getActiveMember() {
        if (teamdetails == null) return 0;
        return (int) teamdetails.stream()
                .filter(td -> Boolean.TRUE.equals(td.getStatus()))
                .count();
    }
}
